CREATE OR REPLACE FUNCTION add2Var(v_v1 INTEGER, v_v2 INTEGER) RETURN INTEGER IS
BEGIN
  return (v_v1 + v_v2);
END;
  
SET SERVEROUT ON;

BEGIN
  DBMS_OUTPUT.put_line(add2Var(10, 15));
END;

DROP FUNCTION add2Var;