SET SERVEROUTPUT ON;
SET VERIFY OFF;
DECLARE
    v_itemName varchar(100);
BEGIN
    SELECT ITEM_NAME INTO v_itemName FROM BMS_CP_COMPONENT_CODE WHERE ITEM_NO = '00121';
    IF SQL%FOUND THEN
        DBMS_OUTPUT.PUT_LINE('有找到資料');
        DBMS_OUTPUT.PUT_LINE('ItemName = ' || v_itemName);
    END IF;
    DELETE FROM BMS_CP_COMPONENT_CODE WHERE ITEM_NO = '00AAA';
    IF SQL%NOTFOUND THEN
        DBMS_OUTPUT.PUT_LINE('沒找到資料，無法DELETE。');
    END IF;
END;